### GET hello
GET http://localhost:8888/hello

### GET gw
GET http://localhost:8888/gw

### GET ga
GET http://localhost:8888/gw/hello

### POST phoenix-rpc
POST http://localhost:8888/gw/phoenix-rpc/cn.zyszero.phoenix.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}

### POST direct
POST http://localhost:8888/gw/direct/cn.zyszero.phoenix.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}


### POST direct backend
POST http://localhost:8888/gw/direct/cn.zyszero.phoenix.rpc.demo.api.UserService?backend=http://192.168.36.177:8081/phoenix-rpc
Content-Type: application/json

{
"service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
"methodSign": "findById@1_int",
"args": [
100
]
}