### GET hello
GET http://localhost:8888/hello

### GET gw
GET http://localhost:8888/gw


### POST user
POST http://localhost:8888/gw/cn.zyszero.phoenix.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.zyszero.phoenix.rpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [
    100
  ]
}